export async function checkPageContent(url) {
  const flags = []; let score = 0
  try {
    const controller = new AbortController()
    setTimeout(() => controller.abort(), 10000)
    const res = await fetch(url.startsWith('http') ? url : `https://${url}`, {
      signal: controller.signal,
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; ScamShieldBot/1.0)' }
    })
    const html = await res.text()
    const text = html.toLowerCase()

    // ── 1. WhatsApp image filenames ──────────────────
    const whatsappImgs = (html.match(/WhatsApp[_\s]?Image/gi) || []).length
    if (whatsappImgs >= 3) {
      flags.push({ icon:'📱', label:'Product Photos from WhatsApp', detail:`${whatsappImgs} product images are WhatsApp photos (filenames contain "WhatsApp_Image") — real brands use professional photography`, severity:'high', category:'content' })
      score -= 30
    } else if (whatsappImgs >= 1) {
      flags.push({ icon:'📱', label:'WhatsApp Images Found', detail:'Site uses WhatsApp photos as product images — sign of an unprofessional or fake store', severity:'medium', category:'content' })
      score -= 15
    }

    // ── 2. AI-generated images (ChatGPT/Copilot/DALL-E) ──
    const aiImgPatterns = ['chatgpt_image', 'copilot_', 'dall-e', 'dalle_', 'midjourney', 'aigenerated', 'ai_image']
    const aiImgFound = aiImgPatterns.filter(p => html.toLowerCase().includes(p))
    if (aiImgFound.length > 0) {
      flags.push({ icon:'🤖', label:'AI-Generated Store Images', detail:`Store images were generated by AI tools (${aiImgFound[0]} filename found) — no real brand uses AI-generated images directly`, severity:'high', category:'content' })
      score -= 25
    }

    // ── 3. Fake star ratings stuffed in wrong fields ──
    const fakeRatingPattern = /\.4\.\d⭐|vendor.*⭐.*\d{3,}/i
    if (fakeRatingPattern.test(html)) {
      flags.push({ icon:'⭐', label:'Fake Ratings in Wrong Fields', detail:'Star ratings stuffed into vendor/brand fields — site has no real review system, all ratings are fabricated', severity:'high', category:'fake_reviews' })
      score -= 20
    }

    // ── 4. Brand identity mismatch ───────────────────
    const brandMatches = html.match(/©\s*\d{4}\s*[-–]?\s*([A-Z][A-Za-z\s]+)\./i) || []
    const footerBrand = brandMatches[1]?.trim().toLowerCase() || ''
    const titleMatch = html.match(/<title>([^<]+)<\/title>/i)
    const titleText = titleMatch?.[1]?.toLowerCase() || ''
    if (footerBrand && titleText && footerBrand.length > 2 && !titleText.includes(footerBrand.split(' ')[0])) {
      flags.push({ icon:'🏢', label:'Brand Identity Mismatch', detail:`Header brand and footer brand are different — footer says "${brandMatches[1]?.trim()}" but site title is different. Copied template, fake store.`, severity:'high', category:'identity' })
      score -= 25
    }

    // ── 5. Social links pointing to Shopify defaults ──
    const shopifySocialLinks = (html.match(/facebook\.com\/shopify|instagram\.com\/shopify|twitter\.com\/shopify|youtube\.com\/user\/shopify/gi) || []).length
    if (shopifySocialLinks >= 2) {
      flags.push({ icon:'📱', label:'Fake Social Media Links', detail:`${shopifySocialLinks} social media links point to Shopify's own accounts — store owner never set up real social profiles`, severity:'high', category:'identity' })
      score -= 20
    }

    // ── 6. Extreme discounts on everything ───────────
    const discounts = [...html.matchAll(/sale\s*[-–]?\s*(\d+)%/gi)].map(m => parseInt(m[1]))
    const extremeDiscounts = discounts.filter(d => d >= 60)
    if (extremeDiscounts.length >= 3) {
      flags.push({ icon:'💸', label:'Extreme Discounts on All Products', detail:`${extremeDiscounts.length} products showing ${Math.max(...extremeDiscounts)}%+ discounts — no real business permanently discounts everything by 60-82%`, severity:'high', category:'price' })
      score -= 25
    }

    // ── 7. Fake urgency/pressure tactics ─────────────
    const urgencyPatterns = [
      { pattern: /\d+\s*sold in last\s*\d+\s*min/i, msg: 'Fake "X sold in last Y min" counter' },
      { pattern: /hurrify|hurry.*only.*left|only \d+ left/i, msg: 'Fake stock countdown' },
      { pattern: /\d{3,}\s*customers are viewing/i, msg: 'Fake "X customers viewing" counter' },
      { pattern: /buy\s*1\s*get\s*1|bogo/i, msg: 'BOGO offer (commonly used to deceive on value)' },
    ]
    const foundUrgency = urgencyPatterns.filter(u => u.pattern.test(html))
    if (foundUrgency.length >= 2) {
      flags.push({ icon:'⏰', label:'Multiple Fake Urgency Tactics', detail:`Site uses ${foundUrgency.length} pressure tactics: ${foundUrgency.map(u=>u.msg).join(', ')}`, severity:'high', category:'pressure' })
      score -= 20
    } else if (foundUrgency.length === 1) {
      flags.push({ icon:'⏰', label:'Pressure Tactic Detected', detail:foundUrgency[0].msg + ' — used to rush buyers into purchasing', severity:'medium', category:'pressure' })
      score -= 10
    }

    // ── 8. Recycled reviews across products ──────────
    const reviewNames = ['riya bansal', 'ayush', 'kshitiz', 'harsh agarwal', 'rahul sharma']
    const foundReviewers = reviewNames.filter(n => text.includes(n))
    const reviewCount = (html.match(/customer.*review|testimonial|⭐.*⭐/gi) || []).length
    if (foundReviewers.length >= 2 && reviewCount >= 3) {
      flags.push({ icon:'👥', label:'Copy-Pasted Fake Reviews', detail:`Same reviewers (${foundReviewers.slice(0,2).join(', ')}) appear across multiple products — reviews are fabricated and recycled`, severity:'high', category:'fake_reviews' })
      score -= 20
    }

    // ── 9. No real contact info ───────────────────────
    const hasPhone = /(\+91|0)\d{10}|\d{4}[\s-]\d{6}/.test(text)
    const hasEmail = /[a-z0-9._%+-]+@(?!shopify)[a-z0-9.-]+\.[a-z]{2,}/.test(text)
    const hasAddress = /\d+.*?(road|street|nagar|colony|lane|floor|building)/i.test(text)
    if (!hasPhone && !hasEmail && !hasAddress) {
      flags.push({ icon:'📞', label:'No Real Contact Information', detail:'No phone number, no business email, no physical address — impossible to contact seller after purchase', severity:'high', category:'contact' })
      score -= 25
    }

    // ── 10. Tech products at impossible prices ────────
    const techKeywords = ['ssd','1tb','2tb','iphone','macbook','airpods','ps5','gpu','rtx','smartwatch','laptop']
    const hasTech = techKeywords.some(k => text.includes(k))
    const allPrices = [...text.matchAll(/rs\.?\s?(\d+)|₹\s?(\d+)/g)].map(m => parseInt(m[1]||m[2])).filter(p => p > 0)
    const veryLowPrices = allPrices.filter(p => p < 2000)
    if (hasTech && veryLowPrices.length > 0) {
      flags.push({ icon:'💻', label:'Impossible Tech Product Pricing', detail:`Tech/electronic products listed at ₹${Math.min(...veryLowPrices)} — these products cost 5-20x more at genuine retailers`, severity:'high', category:'price' })
      score -= 30
    }

    // ── 11. Random/gibberish SKUs ─────────────────────
    const gibberishSku = /sku.*[A-Z]{4,}\s+[A-Z]{2,}|bgbvbvc|xyzabc/i.test(html)
    if (gibberishSku) {
      flags.push({ icon:'🔢', label:'Gibberish Product SKUs', detail:'Product SKUs contain random characters (e.g. "BGBVBVC CV") — no real inventory management system', severity:'medium', category:'content' })
      score -= 10
    }

    // ── 12. COD only ─────────────────────────────────
    const hasCod = text.includes('cash on delivery') || text.includes(' cod ')
    const hasOnlinePay = ['upi', 'razorpay', 'stripe', 'credit card', 'debit card', 'net banking', 'paytm'].some(p => text.includes(p))
    if (hasCod && !hasOnlinePay) {
      flags.push({ icon:'💰', label:'Cash on Delivery Only', detail:'Only COD payment available — scammers prefer COD so customers pay before opening the package and discovering a fake product', severity:'high', category:'payment' })
      score -= 20
    }

  } catch (err) { console.error('[PageContent]', err.message) }
  return { flags, score }
}
